python: install setuptools first when bootstrapping
Installing tox indirectly depends on setuptools being installed due to
one of the `scandir` module which is one of its dependency:

 Collecting scandir; python_version < "3.5"
 (from pathlib2;
  python_version < "3"->importlib-metadata>=0.12;
  python_version < "3.8"->tox)
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
     ImportError: No module named setuptools

Install setuptools before tox.

Bug: T304860
Change-Id: I3b68c243f6591a593b74dbf42bf42a8998398643